apiVersion: v2
name: cert-manager
description: A Helm chart for deploying cert-manager and related components
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: cert-manager
    version: "v1.17.1"
    repository: "https://charts.jetstack.io"
    condition: cert-manager.enabled
