apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap
  namespace: argocd
spec:
  destination:
    namespace: argocd
    name: "in-cluster"
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  sources:
  - repoURL: cnoe://
    ref: values
  - repoURL: cnoe://
    path: "addons/charts/application-sets"
    helm:
      valuesObject:
        repoURLGit: cnoe://
      valueFiles:
      - $values/addons/clusters/in-cluster/common.yaml
      - $values/addons/clusters/in-cluster/external-secrets.yaml
      - $values/addons/clusters/in-cluster/kube-prometheus-stack.yaml
      - $values/addons/clusters/in-cluster/metrics-server.yaml
