apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fleet-management-addons
  namespace: argocd
spec:
  destination:
    namespace: argocd
    name: "in-cluster"
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  sources:
  - repoURL: cnoe://
    ref: values
  - repoURL: cnoe://
    path: "addons/charts/application-sets"
    helm:
      valuesObject:
        repoURLGit: cnoe://
      valueFiles:
      - $values/addons/clusters/fleet/common.yaml
      - $values/addons/clusters/fleet/cert-manager.yaml
      - $values/addons/clusters/fleet/metrics-server.yaml
      - $values/addons/clusters/fleet/atascado.yaml
