apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-test
  namespace: argocd
  labels:
    cnoe.io/stackName: vcluster-generator
    cnoe.io/applicationName: argocon2025
spec:
  project: default
  sources:
    - chart: vcluster
      repoURL: https://charts.loft.sh
      targetRevision: 0.23.0
      helm:
        valuesObject:
          sync:
            fromHost:
              nodes:
                enabled: true # Required for virtualScheduler
          controlPlane:
            distro:
              k8s:
                enabled: true
                version: v1.30.10
            advanced:
              virtualScheduler: # For Keptn support: https://keptn.sh/stable/docs/installation/configuration/vcluster/
                enabled: true
            proxy:
              extraSANs:
              - cluster-test.cnoe.localtest.me
            statefulSet:
              scheduling:
                podManagementPolicy: OrderedReady
          exportKubeConfig:
            server: https://cluster-test.cnoe.localtest.me:443
  destination:
    server: https://kubernetes.default.svc
    namespace: cluster-test
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true