# Values for vcluster generation

# Set to false if you want to limit the number of generated vclusters
# Otherwise, all combinations will be created (clouds x regions x environments × versions × organizations)
generateAllCombinations: false

# Maximum number of configmaps to generate if generateAllCombinations is false
maxClusters: 2

# All possible combinations of these values will be used to create vclusters
possibleValues:
  clouds:
    - aws
    - azure
    - gcp

  regions:
    - us-east-1
    - us-west-2
    - eu-west-2

  environments:
    - ci
    - staging
    - production

  versions:
    - "v1.32.0"
    - "v1.31.6"

  organizations:
    - team-1
    - team-2
    - team-3


extraLabels:
  gpuEnabled: 'true'
  clusterType: 'vcluster'
  workload: 'true'

extraAnnotations:
  accountId: '123456789012'
  vpcId: 'XXXXXXXXXXXXXXXXXXXXX'
  # optional flag to explicitly disable arm64 nodeSelectors
  # arm64Enabled: 'false'

argocd:
  namespace: argocd
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cluster-test

externalSecretsVcluster:
  repoURL: cnoe://
  targetRevision: HEAD
  path: external-secrets-vcluster


vcluster:
  repoURL: https://charts.loft.sh
  targetRevision: "0.23.0"
