{
 "title": "Argo CD Application Status",
 "description": "Argo CD Application Status",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(argocd_app_info:detailed,application)"
    }
   },
   {
    "name": "project",
    "label": "AppProject",
    "query": {
     "query": "label_values(argocd_app_info,project)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Deny Sync Windows", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Clusters",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(argocd_appproject_sync_windows{kind=\"deny\",cluster!=\"\", project=~\".*$project.*\"}) by (cluster, project)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "count(argocd_appproject_sync_windows{kind=\"deny\",application!=\"\", project=~\".*$project.*\"}) by (application, project)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Applications with Issues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Out of Sync/Unhealthy",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "count(argocd_application_out_of_sync{application=~\".*$application.*\", project=~\".*$project.*\"}) by (application, cluster, project, phase, sync_status, health_status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Long Running Deployments",
   "type": "table",
   "description": "Application Deployments that have been running for more than 1 hour but have not yet completed for some reason",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "count(argocd_application_long_running_sync{application=~\".*$application.*\", project=~\".*$project.*\"}) by (application, cluster, project, phase, sync_status, health_status)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}