apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.job.name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  # We don't set completions or activeDeadlineSeconds to ensure the job never completes when magic words match
  backoffLimit: 0  # Don't retry on failure
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      containers:
      - name: atascado
        image: {{ .Values.job.image }}
        command: 
          - "sh"
          - "-c"
          - |
            CURRENT_NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
            echo "Current namespace: $CURRENT_NAMESPACE"
            echo "Magic Word 1: {{ .Values.magicWord1 }}"
            echo "Magic Word 2: {{ .Values.magicWord2 }}"
            
            # Check if the magic words match
            if [ "{{ .Values.magicWord1 }}" = "{{ .Values.magicWord2 }}" ] && [ "{{ .Values.magicWord1 }}" != "" ]; then
              echo "Magic words match! This job will never complete."
              while true; do 
                echo "Still running in stuck mode due to matching magic words..."
                sleep 60
              done
            else
              echo "Magic words don't match. This job will complete normally."
              echo "Job completed successfully!"
              exit 0
            fi
