apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-store
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-store
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-store
  apiGroup: rbac.authorization.k8s.io
