# Default values for addon-atascado
# This is a YAML-formatted file.

# Magic words that will cause the job to get stuck if they match
magicWord1: "cluster-1"
magicWord2: "hocus-pocus"

configMap:
  name: atascado-config
  data:
    message: "This is a demo for ArgoCD stuck in progressing state"

job:
  name: atascado-job
  image: busybox:latest
  # Command will be constructed in the template based on magic words
