apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "fuera-de-onda.fullname" . }}-configmap-creator
  labels:
    {{- include "fuera-de-onda.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "fuera-de-onda.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "fuera-de-onda.fullname" . }}-configmap-creator
  apiGroup: rbac.authorization.k8s.io
