apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "fuera-de-onda.fullname" . }}-configmap-creator
  labels:
    {{- include "fuera-de-onda.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["*"]
