{{- if .Values.job.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fuera-de-onda.serviceAccountName" . }}
  labels:
    {{- include "fuera-de-onda.labels" . | nindent 4 }}
{{- end }}
